src/Entity/Historial.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HistorialRepository")
 */
class Historial
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $factura;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RenglonHistorial", mappedBy="historial", orphanRemoval=true)
     */
    private $RenglonHistorial;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cliente", inversedBy="historiales")
     */
    private $Cliente;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $eliminado;

    /**
     * @ORM\ManyToOne(targetEntity=Proveedor::class, inversedBy="historiales")
     */
    private $proveedor;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="Historiales")
     */
    private $usuario;

    public function __construct()
    {
        $this->RenglonHistorial = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getFactura(): ?bool
    {
        return $this->factura;
    }

    public function setFactura(bool $factura): self
    {
        $this->factura = $factura;

        return $this;
    }

    /**
     * @return Collection|RenglonHistorial[]
     */
    public function getRenglonHistorial(): Collection
    {
        return $this->RenglonHistorial;
    }

    public function addRenglonHistorial(RenglonHistorial $renglonHistorial): self
    {
        if (!$this->RenglonHistorial->contains($renglonHistorial)) {
            $this->RenglonHistorial[] = $renglonHistorial;
            $renglonHistorial->setHistorial($this);
        }

        return $this;
    }

    public function removeRenglonHistorial(RenglonHistorial $renglonHistorial): self
    {
        if ($this->RenglonHistorial->contains($renglonHistorial)) {
            $this->RenglonHistorial->removeElement($renglonHistorial);
            // set the owning side to null (unless already changed)
            if ($renglonHistorial->getHistorial() === $this) {
                $renglonHistorial->setHistorial(null);
            }
        }

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->Cliente;
    }

    public function setCliente(?Cliente $Cliente): self
    {
        $this->Cliente = $Cliente;

        return $this;
    }

    public function getEliminado(): ?bool
    {
        return $this->eliminado;
    }

    public function setEliminado(bool $eliminado): self
    {
        $this->eliminado = $eliminado;

        return $this;
    }

    public function getProveedor(): ?Proveedor
    {
        return $this->proveedor;
    }

    public function setProveedor(?Proveedor $proveedor): self
    {
        $this->proveedor = $proveedor;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }
}

src/Entity/RenglonHistorial.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RenglonHistorialRepository")
 */
class RenglonHistorial
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detalle;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cantidad;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="No puede dejar en blanco")
     */
    private $precio;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Producto", inversedBy="renglonHistoriales")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull(message="Elija un producto")
     * 
     */
    private $Producto;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Historial", inversedBy="RenglonHistorial")
     * @ORM\JoinColumn(nullable=false)
     */
    private $historial;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDetalle(): ?string
    {
        return $this->detalle;
    }

    public function setDetalle(?string $detalle): self
    {
        $this->detalle = $detalle;

        return $this;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(?int $cantidad): self
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getProducto(): ?Producto
    {
        return $this->Producto;
    }

    public function setProducto(?Producto $Producto): self
    {
        $this->Producto = $Producto;

        return $this;
    }

    public function getHistorial(): ?Historial
    {
        return $this->historial;
    }

    public function setHistorial(?Historial $historial): self
    {
        $this->historial = $historial;

        return $this;
    }
}

src/Form/RenglonHistorialType.php
<?php

namespace App\Form;

use App\Entity\RenglonHistorial;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use App\Entity\Producto;

use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;

class RenglonHistorialType extends AbstractType
{
    private $em;
    
    /**
     * The Type requires the EntityManager as argument in the constructor. It is autowired
     * in Symfony 3.
     * 
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('detalle', TextType::class, ['empty_data' => ''])
            ->add('cantidad', NumberType::class)
            ->add('precio', NumberType::class)
            
            ->addEventListener(FormEvents::PRE_SET_DATA, array($this, 'onPreSetData'))
            ->addEventListener(FormEvents::PRE_SUBMIT, array($this, 'onPreSubmit'))
        ;
    }
    
    protected function addElements(FormInterface $form, Producto $producto = null) {
        // 4. Add the province element
        $form->add('Producto', EntityType::class, array(
            'label' => 'Producto',
            'required' => true,
            'data' => $producto,
            'placeholder' => 'Seleccione un Producto...',
            'class' => Producto::class,
            'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('p')
                            ->where('p.eliminado = false')
                            ->orderBy('p.nombre', 'ASC');
                    },
//            'choice_label' => function ($producto) {
//                      return $producto->getNombre();
//                },
        ));

        if($producto)
            {$idPto = $producto->getId();}
        else{$idPto = 0;}
        
        $form->add('precio', NumberType::class, array(
            'label' => 'Precio',
            'required' => true,
 //           'data' => $producto->getPrecio()
        ));
   
    }
    
    function onPreSubmit(FormEvent $event) {
        $form = $event->getForm();
        $data = $event->getData();
        
        
         //Search for selected City and convert it into an Entity
        $producto = $this->em->getRepository(Producto::class)->find($data['Producto']);
        $this->addElements($form, $producto);
     }
     
    function onPreSetData(FormEvent $event) {
        if (null != $event->getData()) {
    
            $renglonHistorial = $event->getData();
            $form = $event->getForm();

            // When you create a new person, the City is always empty
            $producto = $renglonHistorial->getProducto() ? $producto->getProducto() : null;

            $this->addElements($form, $producto);
        }
    }
    
    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_renglonHistorial';
    }
    

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RenglonHistorial::class,
        ]);
    }
}

src/Controller/RenglonHistorialController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Historial;
use App\Entity\Producto;
use App\Entity\RenglonHistorial;
use App\Form\RenglonHistorialType;
use Symfony\Component\HttpFoundation\JsonResponse;

class RenglonHistorialController extends AbstractController
{
    
    /**
     * @Route("/renglonHistorial/nuevo/{historial_id}", name="renglonHistorial_nuevo")
     */
    public function renglonHistorialNuevoAction(Request $request, $historial_id)
    {
        $renglonHistorial = new RenglonHistorial();

        $entityManager = $this->getDoctrine()->getManager();

        $form = $this->createForm(RenglonHistorialType::class, $renglonHistorial);

        $form->handleRequest($request);
        
        $historial = $entityManager
                        ->getRepository(Historial::class)
                        ->find($historial_id);
        
        $total = 0;
        foreach ($historial->getRenglonHistorial() as $renglon) {
            $total += $renglon->getPrecio();
        }
        
        if($form->isSubmitted() && $form->isValid()){

            $renglonHistorial = $form->getData();
            $renglonHistorial->setHistorial($historial);
             
            $producto = $entityManager
                        ->getRepository(Producto::class)
                        ->find($renglonHistorial->getProducto());
        
            if($producto->getControlStock()){
                if($historial->getProveedor() != null){
                    $cantidad = $producto->getCantidad() + $renglonHistorial->getCantidad();
                }else{
                    $cantidad = $producto->getCantidad() - $renglonHistorial->getCantidad();    
                }
                $producto->setCantidad($cantidad);
                $entityManager->persist($producto);
            }
            
            $entityManager->persist($renglonHistorial);
            $entityManager->flush();
            
            return $this->redirectToRoute('renglonHistorial_nuevo', array('historial_id' => $historial_id));

        }
        
        return $this->render('renglon_historial/nuevo.html.twig',[
            'form' => $form->createView(),
            'historial' => $historial,
            'total' => $total,
        ]);
    }
    
    /**
     * @Route("/renglonHistorial/eliminar/{id}", name="renglonHistorial_eliminar")
     */
    public function renglonHistorialEliminarAction(Request $request, $id)
    {    
        $entityManager = $this->getDoctrine()->getManager();

        $renglonHistorial = $entityManager
            ->getRepository(RenglonHistorial::class)
            ->find($id);
        
        $historial = $renglonHistorial->getHistorial();
        
        $producto = $entityManager
                        ->getRepository(Producto::class)
                        ->find($renglonHistorial->getProducto());
        
            if($producto->getControlStock()){
                if($historial->getProveedor() != null){
                    $cantidad = $producto->getCantidad() - $renglonHistorial->getCantidad();
                }else{
                    $cantidad = $producto->getCantidad() + $renglonHistorial->getCantidad();    
                }
                $producto->setCantidad($cantidad);
                $entityManager->persist($producto);
            }

        $historial->removeRenglonHistorial($renglonHistorial);
        //$entityManager->remove($renglonHistorial);

        $entityManager->flush();

        return $this->redirectToRoute('renglonHistorial_nuevo', array('historial_id' => $historial->getId()));
    }
    
    /**
     * Returns a JSON string with the neighborhoods of the City with the providen id.
     * @Route("/renglonHitorial/dependent", name="renglonHitorial_list_precios", defaults={"_controller": "App:Controller:RenglonHitorialController:listPrecioOfRenglonHitorialAction"}, methods="GET")
     * @param Request $request
     * @return JsonResponse
     */
    public function listPrecioOfRenglonHitorialAction(Request $request)
    {
        // Get Entity manager and repository
        $entityManager = $this->getDoctrine()->getManager();
        
        

// Search the neighborhoods that belongs to the city with the given id as GET parameter "cityid"
        $producto = $entityManager
                        ->getRepository(Producto::class)
                        ->find($request->query->get("idPto"));
        
//        $localidades = $localidadesRepository->createQueryBuilder("q")
//            ->where("q.idDepartamento = :idDto")
//            ->setParameter("idDto", $request->query->get("idDto"))
//            ->getQuery()
//            ->getResult();
        
        // Serialize into an array the data that we need, in this case only name and id
        // Note: you can use a serializer as well, for explanation purposes, we'll do it manually
        $responseArray = array();
//        foreach($localidades as $localidad){
        $responseArray[] = array(
            "precio" => $producto->getPrecio(),
            "detalle" => $producto->getDescripcion()
        );
//        }
        
        // Return array with structure of the neighborhoods of the providen city id
        return new JsonResponse($responseArray);

        // e.g
        // [{"id":"3","name":"Treasure Island"},{"id":"4","name":"Presidio of San Francisco"}]
    }
}

templates/renglon_historial/nuevo.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block navActivo %}
    <a class="nav-item nav-link" href="{{ path('home') }}">Home</a>
    {% if historial.proveedor == null %}
        <a class="nav-item nav-link active" href="{{ path('clientes_listar') }}">Clientes</a>
        <a class="nav-item nav-link" href="{{ path('proveedor_listar') }}">Proveedores</a>
    {% else %}
        <a class="nav-item nav-link" href="{{ path('clientes_listar') }}">Clientes</a>
        <a class="nav-item nav-link active" href="{{ path('proveedor_listar') }}">Proveedores</a>    
    {% endif %}
    <a class="nav-item nav-link" href="{{ path('productos_listar') }}">Productos / Servicios</a>
    <a class="nav-item nav-link" href="{{ path('app_logout') }}">Salir</a>
{% endblock %}

{% block body %}
<div class="card bg-light mb-12">
        
    <div class="card-body">
    
        <h2>Historial:</h2>
                 
            <div class="form-row">
                <div class="form-group col-md-3">
                    {% if historial.proveedor == null %}
                    <h4>Cliente:  </h4>
                    {{ historial.Cliente }}
                    {% else %}
                    <h4>Proveedor:  </h4>
                    {{ historial.proveedor }}
                    {% endif %}
                </div>
                <div class="form-group col-md-3">
                    <h4>Fecha:  </h4>
                    {{ historial.fecha.format('d/m/Y') }}
{#                   {{object.date_attribute.format('d/m/Y')}}#}
                </div>
            </div>
                
            
            
            <table class="table table-striped">

                <thead class="thead-dark">
                    
                    <tr>
                        <th scope="col">Producto</th>
                        <th scope="col">Detalle</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Precio Unitario</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Opciones</th>

                    </tr>
                </thead>

                <tbody>
                    {% set total = 0 %}
                    {% for renglon in historial.renglonHistorial %}
                        <tr>
                            <th scope="row">{{ renglon.Producto }}</th>
                            <td>{{ renglon.detalle }}</td>
                            <td>{{ renglon.cantidad }}</td>
                            <td>{{ renglon.precio }}</td>
                            <td>{{ renglon.precio * renglon.cantidad}}</td>

                            <td>
                                <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path('renglonHistorial_eliminar', {'id' : renglon.id }) }}'">Quitar</button>
                                
                            </td>
                        </tr>
                        
                        {% set total = total + (renglon.precio * renglon.cantidad) %}
                        
                    {% else %}
                        <tr>
                            <th scope="row" colspan="5">No se encontraron resultados.</th>
                            
                        </tr>
                    {% endfor %}
                    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
   
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th style="text-align:center">Total</th>
                        <th>
                            {#<input type="number" id="precio_total" name="Precio Total" class="form-control" value="{{ total }}" disabled> #}
                            {{ total }}
                        </th>
                    </tr>
                    <tr>
                        <th scope="row"> 
                            {{ form_widget(form.Producto, {'attr': {'class': form_errors(form.detalle) ? 'form-control is-invalid' : 'form-control'}}) }}
                        </th>
                        <td>
                            {{ form_widget(form.detalle, {'attr': {'class': form_errors(form.detalle) ? 'form-control is-invalid' : 'form-control'}}) }} 
                        </td>
                        <td>
                            {{ form_widget(form.cantidad, {'attr': {'class': form_errors(form.cantidad) ? 'form-control is-invalid' : 'form-control'}}) }} 
                        </td>
                        <td>
                            {{ form_widget(form.precio, {'attr': {'class': form_errors(form.precio) ? 'form-control is-invalid' : 'form-control'}}) }} 
                        </td>
                        <td>
                            <input type="number" id="precio_total" name="Precio Total" class="form-control" disabled> 
                        </td>

                        <td>
                            <button type="submit" class="btn btn-primary" formnovalidate>Agregar</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            
           {{form_end(form)}}  
              
            <div class="form-row">
                {% if historial.proveedor == null %}
                <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path('cliente_historiales', {'id' : historial.cliente.id }) }}'">Volver</button>
                {% else %}
                <button type="button" class="btn btn-secondary" onclick="window.location.href = '{{ path('proveedor_historiales', {'id' : historial.proveedor.id }) }}'">Volver</button>
                {% endif %}
                <div>&nbsp;</div>
                <button type="button" class="btn btn-dark" onclick="window.location.href = '{{ path('historial_facturar', {'id' : historial.id })  }}'">Imprimir</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
{{ parent() }}

<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<script>
    $('#app_renglonHistorial_Producto').change(function () {
        var ProductoSelector = $(this);

        // Request the neighborhoods of the selected city.
        $.ajax({
            url: "{{ path('renglonHitorial_list_precios') }}",
            type: "GET",
            dataType: "JSON",
            data: {
                idPto: ProductoSelector.val()
            },
            success: function (productos) {

                var cantidadField = $('#app_renglonHistorial_cantidad');
                var precioField = $("#app_renglonHistorial_precio");
                
                cantidadField.val('1');
                
                // Remove current options
                //$('#app_renglonHistorial_cantidad').val('0');
                //$("#precio_total").val('0');
                //precioUField.html('');
                
                
                $.each(productos, function (key, producto) {
                   precioField.val(producto.precio);
                   $('#app_renglonHistorial_detalle').val(producto.detalle); 
                });

                var precioNuevo = cantidadField.val() * precioField.val();
                $('#precio_total').val(precioNuevo);

            },
            error: function (err) {
                alert("Error cargando datos ...");
            }
        });
    });
    
    $('#app_renglonHistorial_cantidad').on('change', function(){ 
        var cantidadField = $('#app_renglonHistorial_cantidad');
        var precioField = $("#app_renglonHistorial_precio");
        var precioNuevo = cantidadField.val() * precioField.val();
        $('#precio_total').val(precioNuevo);
    });
    
    $('#app_renglonHistorial_precio').on('change', function(){ 
        var cantidadField = $('#app_renglonHistorial_cantidad');
        var precioField = $("#app_renglonHistorial_precio");
        var precioNuevo = cantidadField.val() * precioField.val();
        $('#precio_total').val(precioNuevo);
    });
    

</script>
{% endblock %}